// L10nCompletenessTests — Phase 9.5.
//
// Asserts every key in Localizable.xcstrings carries translations for all
// 7 target locales (en, zh-Hant, zh-Hans, ja, ko, es, th) and that no
// `<TRANSLATE>` placeholder literals remain from the seed pass.

import Foundation
import Testing

@Suite("Localizable.xcstrings — all 7 locales (Phase 9.5)")
struct L10nCompletenessTests {

    private static let allLocales: Set<String> = [
        "en", "zh-Hant", "zh-Hans", "ja", "ko", "es", "th"
    ]

    private static func catalogURL() throws -> URL {
        // Bundle.module resolves the bundled fixture at
        // `Resources/Localizable.xcstrings.json`. That fixture is a
        // mechanically-generated byte-copy of the shipping catalog
        // `App/Sudoku/Resources/Localizable.xcstrings` (regenerate via
        // `mise run gen:l10n_fixture`; drift is blocked by the `scan:l10n`
        // gate — issue #394). It is NEVER hand-edited, so this test now
        // guards the real shipping source of truth. The `.json`-renamed copy
        // is required because the App catalog lives outside this SwiftPM
        // package and the Xcode Cloud test runner has no source tree.
        guard let url = Bundle.module.url(forResource: "Localizable.xcstrings", withExtension: "json") else {
            throw CocoaError(.fileReadNoSuchFile)
        }
        return url
    }

    @Test
    func all7LocalesPresent() throws {
        let data = try Data(contentsOf: try Self.catalogURL())
        let json = try JSONSerialization.jsonObject(with: data) as? [String: Any]
        let strings = json?["strings"] as? [String: [String: Any]] ?? [:]
        for (key, entry) in strings {
            if let flag = entry["shouldTranslate"] as? Bool, flag == false { continue }
            let localizations = entry["localizations"] as? [String: Any] ?? [:]
            let present = Set(localizations.keys)
            let missing = Self.allLocales.subtracting(present)
            #expect(missing.isEmpty, "Key '\(key)' missing locales: \(missing.sorted())")
        }
    }

    @Test
    func noUntranslatedMarkers() throws {
        let raw = try String(contentsOf: try Self.catalogURL(), encoding: .utf8)
        #expect(!raw.contains("<TRANSLATE>"), "Catalog still contains <TRANSLATE> placeholders")
    }
}
